import { CheckSquare, Building2, Lock, Download } from 'lucide-react';
import { WorkflowState, ApplicantRecord, ActivityLog } from '../../types';

interface ManagerHubProps {
  workflow: WorkflowState;
  updateWorkflow: (updates: Partial<WorkflowState>) => void;
  showToast: (message: string) => void;
  applicants?: ApplicantRecord[];
  currentUserName: string;
  addActivityLog: (log: Omit<ActivityLog, 'id' | 'timestamp'>) => void;
  updateApplicant: (applicantId: string, updates: Partial<ApplicantRecord>) => void;
  selectedApplicantId?: string;
}

export default function ManagerHub({
  workflow,
  updateWorkflow,
  showToast,
  applicants = [],
  currentUserName,
  addActivityLog,
  updateApplicant,
  selectedApplicantId = 'APP-2026-089',
}: ManagerHubProps) {
  const handleExportToPDF = () => {
    // Generate PDF content
    const selectedApplicant = applicants.find(a => a.id === selectedApplicantId);

    if (!selectedApplicant) {
      showToast('❌ No applicant selected');
      return;
    }

    // Create a simple text representation for PDF export
    const pdfContent = `
EMPLOYER APPROVAL REPORT
========================

Applicant Information:
- Name: ${selectedApplicant.name}
- ID: ${selectedApplicant.id}
- Position: ${selectedApplicant.role}
- Job Order: ${selectedApplicant.jobOrder || 'N/A'}

Current Status:
- Phase: ${selectedApplicant.phase}
- Status: ${selectedApplicant.status}
- Handler: ${selectedApplicant.currentHandler}
- Department: ${selectedApplicant.currentDepartment}

Test Scores:
- English Proficiency: ${selectedApplicant.testScores?.englishProficiency || 'N/A'}%
- Trade/Skills: ${selectedApplicant.testScores?.tradeSkills || 'N/A'}%
- IQ/Aptitude: ${selectedApplicant.testScores?.iqAptitude || 'N/A'}%
- Personality/EQ: ${selectedApplicant.testScores?.personalityEQ || 'N/A'}

Workflow Status:
- Medical Cleared: ${workflow.medicalCleared ? 'Yes' : 'No'}
- CV Approved: ${workflow.cvApproved ? 'Yes' : 'No'}
- Employer Accepted: ${workflow.employerAccepted ? 'Yes' : 'No'}

Generated by: ${currentUserName}
Date: ${new Date().toLocaleString()}
    `;

    // Create blob and download
    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `employer-approval-${selectedApplicant.id}-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);

    addActivityLog({
      applicantId: selectedApplicantId,
      action: 'Employer Approval Report Exported',
      performedBy: currentUserName,
      department: 'Management',
      details: `Exported employer approval report for ${selectedApplicant.name} (${selectedApplicant.id})`,
    });

    showToast('✓ Employer approval report exported successfully');
  };

  const handleApproveAndAccept = () => {
    const applicantId = selectedApplicantId;

    // Step 1: Approve CV
    updateWorkflow({ cvApproved: true });
    updateApplicant(applicantId, {
      status: 'CV Approved - Sending to Employer',
      currentHandler: currentUserName,
      currentDepartment: 'Management',
      phaseDescription: 'CV approved by management, being sent to foreign employer',
    });

    addActivityLog({
      applicantId,
      action: 'CV Approved by Management',
      performedBy: currentUserName,
      department: 'Management',
      details: 'Manager reviewed and approved CV quality. Ready for external employer endorsement.',
    });

    // Step 2: Record Employer Acceptance
    setTimeout(() => {
      updateWorkflow({ employerAccepted: true });
      updateApplicant(applicantId, {
        phase: 5,
        status: 'Final Deployment Processing',
        currentHandler: 'Maria Santos',
        currentDepartment: 'Admin',
        phaseDescription: 'Employer confirmed selection. Admin & Accounting modules unlocked for final processing.',
      });

      addActivityLog({
        applicantId,
        action: 'Employer Acceptance Recorded',
        performedBy: currentUserName,
        department: 'Management',
        details:
          'Foreign employer (Saudi - Al-Futtaim Engineering) confirmed hiring decision. MASTER KEY ACTIVATED: Phase 5 modules (Document OCR, Expense Tracking) now unlocked for Admin and Accounting.',
      });

      showToast(
        '✓ CV Approved & Employer Acceptance Recorded! Admin & Accounting modules unlocked (Master Key Activated).'
      );
    }, 1500);
  };

  const cvLocked = !workflow.medicalCleared;
  const bothActionsComplete = workflow.cvApproved && workflow.employerAccepted;

  return (
    <div className="space-y-6 max-w-5xl">
      <div className="mb-6 flex items-end justify-between">
        <div>
          <h2 className="text-3xl font-extrabold tracking-tight">
            <CheckSquare className="w-8 h-8 inline-block mr-2 text-[#10B981]" />
            Manager CV & Employer Approval Hub
          </h2>
          <p className="text-sm text-[#64748B] mt-1 font-medium">
            Quality control gateway and employer acceptance tracker (Master Key)
          </p>
        </div>
        <button
          onClick={handleExportToPDF}
          className="px-5 py-2.5 bg-[#0EA5E9] hover:bg-[#0284C7] text-white text-sm font-bold rounded-lg shadow-lg shadow-[#0EA5E9]/20 flex items-center gap-2"
        >
          <Download className="w-4 h-4" />
          Export to PDF
        </button>
      </div>

      {/* CV Review Section */}
      <div className="bg-white rounded-lg shadow-sm border border-slate-200 p-8 relative">
        {cvLocked && (
          <div className="absolute inset-0 bg-[#F1F5F9]/85 backdrop-blur-sm flex flex-col items-center justify-center z-10 rounded-lg">
            <Lock className="w-8 h-8 text-slate-400 mb-3" />
            <h3 className="font-bold text-[#0F172A]">Waiting for Medical Clearance</h3>
            <p className="text-sm mt-1 text-[#64748B]">Recruitment must complete medical validation first</p>
          </div>
        )}

        <div className="flex items-center justify-between mb-6 border-b-2 border-slate-100 pb-4">
          <div>
            <h3 className="font-black text-[#0F172A] text-lg flex items-center gap-2">
              <Building2 className="w-6 h-6 text-[#0EA5E9]" />
              Locked CV - Quality Control
            </h3>
            <p className="text-xs text-[#64748B] mt-1">CV was locked by Recruitment after submission</p>
          </div>
          {workflow.cvApproved && (
            <span className="px-3 py-1 bg-[#10B981]/10 text-[#10B981] text-xs font-bold uppercase tracking-wider rounded-full border border-[#10B981]/30">
              ✓ Approved
            </span>
          )}
        </div>

        <div className="bg-slate-50 rounded-lg p-6 border border-slate-200 mb-6">
          <div className="grid grid-cols-2 gap-6">
            <div>
              <p className="text-xs font-bold text-[#64748B] uppercase mb-2">Applicant</p>
              <p className="font-bold text-[#0F172A]">Juan Dela Cruz</p>
              <p className="text-sm text-[#64748B]">APP-2026-089 | Industrial Welder</p>
            </div>
            <div>
              <p className="text-xs font-bold text-[#64748B] uppercase mb-2">Target Employer</p>
              <p className="font-bold text-[#0F172A]">Al-Futtaim Engineering</p>
              <p className="text-sm text-[#64748B]">Saudi Arabia | JO-2026-0042</p>
            </div>
          </div>
          <div className="mt-4 pt-4 border-t border-slate-300">
            <p className="text-xs font-bold text-[#64748B] uppercase mb-2">CV Summary (Read-Only)</p>
            <p className="text-sm text-[#0F172A]">
              Experienced industrial welder with 5+ years in structural fabrication. TESDA NCII certified with
              expertise in SMAW, GMAW, and FCAW processes. Strong safety record and blueprint reading skills.
            </p>
          </div>
        </div>


        {bothActionsComplete && (
          <div className="bg-[#10B981]/10 border border-[#10B981]/30 rounded-lg p-6 mb-6">
            <p className="text-sm text-[#10B981] font-bold mb-2">✓ Actions Complete</p>
            <p className="text-sm text-[#64748B]">
              CV has been approved and employer acceptance recorded. Phase 5 modules are now unlocked for Admin and
              Accounting departments.
            </p>
          </div>
        )}
      </div>

      {/* Action Button */}
      {!bothActionsComplete && (
        <div className="bg-white rounded-lg shadow-sm border border-slate-200 p-8">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-black text-[#0F172A] text-lg mb-2">Master Key Action</h3>
              <p className="text-sm text-[#64748B]">
                This action serves as the <span className="font-bold text-[#EF4444]">Master Key</span> that unlocks
                final deployment processing
              </p>
            </div>
            <button
              onClick={handleApproveAndAccept}
              disabled={cvLocked}
              className="px-8 py-4 bg-[#10B981] text-white text-sm font-bold hover:bg-[#059669] shadow-lg rounded-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              <CheckSquare className="w-5 h-5" />
              Approve CV & Record Employer Acceptance
            </button>
          </div>
        </div>
      )}

      {/* Status Panel */}
      <div className="bg-white rounded-lg shadow-sm border border-slate-200 p-8">
        <h3 className="font-black text-[#0F172A] text-lg mb-4">Workflow Status</h3>
        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
            <span className="text-sm font-bold text-[#64748B]">Medical Clearance</span>
            <span
              className={`px-3 py-1 text-xs font-bold rounded-full ${
                workflow.medicalCleared
                  ? 'bg-[#10B981]/10 text-[#10B981]'
                  : 'bg-slate-200 text-slate-500'
              }`}
            >
              {workflow.medicalCleared ? '✓ Cleared' : 'Pending'}
            </span>
          </div>
          <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
            <span className="text-sm font-bold text-[#64748B]">CV Approved</span>
            <span
              className={`px-3 py-1 text-xs font-bold rounded-full ${
                workflow.cvApproved
                  ? 'bg-[#10B981]/10 text-[#10B981]'
                  : 'bg-slate-200 text-slate-500'
              }`}
            >
              {workflow.cvApproved ? '✓ Approved' : 'Pending'}
            </span>
          </div>
          <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
            <span className="text-sm font-bold text-[#64748B]">Employer Acceptance</span>
            <span
              className={`px-3 py-1 text-xs font-bold rounded-full ${
                workflow.employerAccepted
                  ? 'bg-[#10B981]/10 text-[#10B981]'
                  : 'bg-slate-200 text-slate-500'
              }`}
            >
              {workflow.employerAccepted ? '✓ Accepted' : 'Pending'}
            </span>
          </div>
          <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
            <span className="text-sm font-bold text-[#64748B]">Phase 5 Modules</span>
            <span
              className={`px-3 py-1 text-xs font-bold rounded-full ${
                workflow.employerAccepted
                  ? 'bg-[#10B981]/10 text-[#10B981]'
                  : 'bg-red-100 text-red-600'
              }`}
            >
              {workflow.employerAccepted ? '🔓 Unlocked' : '🔒 Locked'}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
