export const SIDEBAR_CONFIG = {
  "/manager": [
    { to: "/manager", label: "Dashboard", icon: "LayoutDashboard", group: "" },
    { to: "/manager/applicant-list", label: "Applicant List", icon: "Users", group: "" },
    { to: "/manager/applicant-profile", label: "Applicant Profile", icon: "FolderSearch", group: "" },
    { to: "/manager/cv-encoding", label: "CV Encoding", icon: "FileText", group: "CV Review & Endorsement" },
    { to: "/manager/endorsement-tracker", label: "Endorsement Tracker", icon: "KanbanSquare", group: "CV Review & Endorsement" },
    { to: "/manager/document-ocr", label: "Document OCR", icon: "ScanText", group: "Document Processing" },
    { to: "/manager/3-2-1-alerts", label: "3-2-1 Alerts", icon: "BellRing", group: "Document Processing" },
    { to: "/manager/employer-hub", label: "CV & Employer Hub", icon: "CheckSquare", group: "Oversight Controls" },
    { to: "/manager/predictive-timeline", label: "Predictive Timeline", icon: "TrendingUp", group: "Oversight Controls" },
    { to: "/manager/deployment-history", label: "Deployment History", icon: "History", group: "Oversight Controls" },
    { to: "/manager/operational-reports", label: "Operational Reports", icon: "FileBarChart", group: "Oversight Controls" },
    { to: "/manager/user-management", label: "User Management", icon: "Users", group: "Oversight Controls" },
  ],
  "/recruitment": [
    { to: "/recruitment", label: "Dashboard" },
    { to: "/recruitment/registration", label: "Registration" },
    { to: "/recruitment/applicant-list", label: "Applicant List" },
    { to: "/recruitment/applicant-profile", label: "Applicant Profile" },
    { to: "/recruitment/screening-panel", label: "Screening Panel" },
    { to: "/recruitment/intake-matching", label: "Intake & Matching" },
    { to: "/recruitment/applicant-profiling", label: "Applicant Profiling" },
  ],
  "/administration": [
    { to: "/administration", label: "Dashboard" },
    { to: "/administration/administrative-compliance-center", label: "Compliance Center" },
    { to: "/administration/applicant-list", label: "Applicant List" },
    { to: "/administration/applicant-profile", label: "Applicant Profile" },
    { to: "/administration/agency-configuration", label: "Agency Config" },
    { to: "/administration/document-requirements", label: "Document Requirements" },
    { to: "/administration/evaluation-workflow", label: "Evaluation & Workflow" },
    { to: "/administration/job-orders", label: "Job Orders" },
    { to: "/administration/employer-profiles", label: "Employer Profiles" },
    { to: "/administration/fit-to-work", label: "Fit-to-Work" },
    { to: "/administration/document-ocr", label: "Document OCR" },
    { to: "/administration/3-2-1-alerts", label: "3-2-1 Alerts" },
  ],
  "/accounting": [
    { to: "/accounting", label: "Dashboard" },
    { to: "/accounting/applicant-list", label: "Applicant List" },
    { to: "/accounting/applicant-profile", label: "Applicant Profile" },
    { to: "/accounting/financials", label: "Financials" },
    { to: "/accounting/expense-ledger", label: "Expense Ledger" },
  ],
  "/super-admin": [
    { to: "/super-admin", label: "Dashboard" },
    { to: "/super-admin/tenant-management", label: "Tenant Management" },
    { to: "/super-admin/agency-onboarding", label: "Agency Onboarding" },
    { to: "/super-admin/audit-ledger", label: "Audit Ledger" },
  ]
};
